samples:
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_GC_noERCC_Rep1_M36_R1_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_GC_noERCC_Rep1_M36_R2_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_GC_noERCC_Rep2_M37_R1_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_GC_noERCC_Rep2_M37_R2_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_FLT_noERCC_Rep1_M25_R1_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_FLT_noERCC_Rep1_M25_R2_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_FLT_noERCC_Rep2_M26_R1_raw.fastq.gz
 - GLDS-168_rna_seq_Mmus_C57-6J_LVR_RR1_FLT_noERCC_Rep2_M26_R2_raw.fastq.gz
osd_id:
 - OSD-168
 - OSD-168
 - OSD-168
 - OSD-168
 - OSD-168
 - OSD-168
 - OSD-168
 - OSD-168
reads:
 - R1
 - R2
 - R1
 - R2
 - R1
 - R2
 - R1
 - R2
rep:
 - Rep1
 - Rep1
 - Rep2
 - Rep2
 - Rep1
 - Rep1
 - Rep2
 - Rep2
variable:
 - control
 - control
 - control
 - control
 - spaceflight
 - spaceflight
 - spaceflight
 - spaceflight
